name: tests

on:
  push:
    branches: ["master"]
    paths:
      - '**.go'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch: {}

jobs:
  lint:
    name: "Lint"
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: projectdiscovery/actions/setup/go@v1
      - uses: projectdiscovery/actions/golangci-lint/v2@v1

  tests:
    name: "Tests"
    needs: ["lint"]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ["1.24", "1.25", "stable"]
    steps:
      - uses: actions/checkout@v6
      - uses: projectdiscovery/actions/setup/go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v -race .
      - run: go test -run ^$ -bench=. -benchmem -cpuprofile=cpu.out -memprofile=mem.out
        env:
          GOMAXPROCS: 4
      - uses: actions/upload-artifact@v4
        with:
          name: fastcache-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.go-version }}-profiles
          path: |
            cpu.out
            mem.out
          overwrite: true

  benchmarks:
    name: "Benchmarks"
    needs: ["tests"]
    if: ${{ github.event_name != 'push' }}
    uses: ./.github/workflows/benchmarks.yaml
